PatrickAlphaC/hardhat-nft-fcc

- contracts/RandomIpfsNft.sol
I saw this typo made on one of your videos from the chainlink hackathon
> Arracy changed to array line

- contracts/RandomIpfsNft.sol
Immutable keyword was missing.
> Added Immutable to the mintFee variable.

- contracts/RandomIpfsNft.sol
Changed tokenCounter visiblity from public to private.
> Changed the visiblity of tokenCounter variable.

- test/unit/basicNft.test.js
Added test for constructor and wrapped existing test for mintNft with describe.
> Added more test and made some improvement

- contracts/BasicNft.sol
Moved updating the tokenCounter before minting, and removed return tokenCounter from mintNft function.
> Removed return tokenCounter from mintNFT.

- contracts/DynamicSvgNft.sol
Moved emit event after _safeMint.
> Moved emit event after _safeMint.

- contracts/DynamicSvgNft.sol
Converted the require statement into a revert statement.
> Converts the require into a revert statement

- contracts/RandomIpfsNft.sol
Delete unused mapping "s_tokenIdToBreed", as nowhere it is being used.
> Delete unused mapping

- utils/uploadToPinata.js
Corrected storeTokenUriMetadata function spelling.
> Corrected storeTokenUriMetadata function spelling

- deploy/03-deploy-random-ipfs-nft.js
Corrected function spelling storeTokenUriMetadata after making a correction in uploadToPinata.js file as well.
> Corrected function spelling

- deploy/04-mint.js
Removed unused parameter deployments from module.exports in 04-mint.js.
> Removed deployments from module.exports

- test/unit/randomIpfs.test.js
Updated the RandomIpfs tests according the PR #31
> Updated the RandomIpfs tests according the PR #31 & #32

- contracts/RandomIpfsNft.sol
- test/unit/randomIpfs.test.js
Please let me know if my edits are wrong, but I believe that that should be the correct numbers now.
> Updated math for getBreedFromModdedRng()

- test/unit/randomIpfs.test.js
Removed unused require **networkConfig** from helper-hardhat-config in randomIpfs.test.
> Removed unused require in randomIpfs.test

- test/unit/basicNft.test.js
Added a unit test for the basic NFT, where balanceOf and ownerOf methods are tested. Also fixed small typo.
> Add unit tests for balanceOf and ownerOf methods

- test/unit/basicNft.test.js
> Edited 'owenerOf' index in BasicNft unit test

- test/unit/basicNft.test.js
describe("Constructor"), instead of, describe("Construtor)
> Update string error

- contracts/sublesson/CallAnything.sol
The comment is pointing out that it is important to not put any spaces in "transfer(address,uint256)" Got kind of stuck here and it came as a complete gotcha to me
> Added a comment

- .env.example
- .env.exmaple
- README.md
- hardhat.config.ts
- helper-hardhat-config.ts
Added 1 file and Updated 3 files:
1. .env.example
2. hardhat.config.ts
3. helper-hardhat-config.ts
4. README.md
> Sepolia Update - Typescript Branch

- .solhint.json
- .solhintignore
- contracts/DynamicSvgNft.sol
- contracts/RandomIpfsNft.sol
- deploy/02-deploy-dynamic-svg-nft.js
- deploy/03-deploy-random-ipfs-nft.js
- test/unit/dynamicSvg.test.js
- test/unit/randomIpfs.test.js
- utils/uploadToNftStorage.js
- utils/uploadToPinata.js
1. There was a few constants & variables ES6 syntax omissions -- fixed
2. Dynamic Svg minting had an event misconfig -- {tokenId log prominent for fronted} fixed
3. Now we have better images mime types support previously we had support only for png mime type.
4. Linting was missing for solidity. Added .solhint.json & .solhintignore
5. and Just enhanced some testing.
;`)
> Typo fix, Event indexing & frontend tokenId support fix, better testing, Linting support & all images mime types support filter & polish!
